### ISSUE TITLE
“内部服务器错误”

### ISSUE THREAD

**Issue by Evayangelion** [wahyd4/aria2-ariang-x-docker-compose#101]
Sorry for bothering.
I installed this image on my CentOS 7.9 server,but I can't get into the Login page, `ip:8000` shows “内部服务器错误” and there is no more info.
On my machine  I don't have `www-data` user so I checked my nginx conf, the user is `www`
So I ran `chown -R www /data` instead of `chown -R www-data <abc>` which in your document
My `docker-compose.yml` is like:
```
version: '3.5'

services:
  nextcloud:
    image: nextcloud:latest
    volumes:
      - ./data/nextcloud:/var/www/html:rw # moutn nextcloud files folder
      - ./data:/data:rw # mount your personal data folder
    restart: always
  aria2:
    image: wahyd4/aria2-ui:nextcloud
    ports:
      - "8000:8000"
      # - "443:443"
    volumes:
      - ./data:/data # mount your personal data folder
    # volumes:
      # - /app/a.db:/app/filebrowser.db
      # - /yoursslkeys/:/app/conf/key
      # - <the folder of aria2.conf and aria2.session>:/app/conf
    environment:
      - DOMAIN=:8000 #domain, for https just bind domain like this https://example.com
      # - PUID=1000 # bind custom linux user id
      # - PGID=1000 # bind custom linux group id
      # - ENABLE_AUTH=true # enable authentication for aria2
      # - RPC_SECRET=Hello # aria2 rpc secret
      # - ARIA2_SSL=false
      # - ARIA2_USER=user # aria2 login user
      # - ARIA2_PWD=pwd  # aria2 login password
    links:
      - nextcloud:file-manager
    restart: always
```
I checked some of your issues but still cant make it, hope for your help
thx!
