### ISSUE TITLE
docker-composer up -d 时错误

### ISSUE THREAD

**Issue by L-Y** [wahyd4/aria2-ariang-x-docker-compose#60]
Removing filerun_db_1
Recreating 4563e74c25ac_filerun_db_1 ...
Recreating 4563e74c25ac_filerun_db_1 ... error

ERROR: for 4563e74c25ac_filerun_db_1  Cannot start service db: b'OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child\'s pid from pipe caused \\"read init-p: connection reset by peer\\"": unknown'

ERROR: for db  Cannot start service db: b'OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child\'s pid from pipe caused \\"read init-p: connection reset by peer\\"": unknown'
ERROR: Encountered errors while bringing up the project.

**Comment by wahyd4** [comment]
Please also paste your docker compose file here. Have you changed anything
in the compose file?

**Comment by L-Y** [comment]
is this?
```yaml
version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    restart: always
    volumes:
      - /data/db:/var/lib/mysql #mysql database
  web:
    depends_on:
      - db
    links:
      - db
    image: afian/filerun
    volumes:
      - ./data:/user-files:rw
    restart: always
  aria2:
    image: wahyd4/aria2-ui:filerun
    links:
      - web:file-manager
    ports:
      - "8000:80"
      - "6800:6800"
      - "443:443"
    environment:
      - DOMAIN=:80
      # - SSL=true
      # - RPC_SECRET=Hello
      # - ARIA2_USER=admin
      # - ARIA2_PWD=password
      # - ENABLE_AUTH=true
    # volumes:
    #   - /some_folder:/root/conf/key
    #   - ~/test/aria2.conf:/root/conf/aria2.conf
    volumes:
      - ./data:/user-files:rw
    restart: always
```
docker version :docker-compose version 1.23.2, build 1110ad01
centos kernel version :3.10.0-229.1.2.el7.x86_64
centos:7.4
